package algorithm460

import (
	"fmt"
	"testing"
)

func TestLFUCache(t *testing.T) {
	lfuCache := Constructor(10)
	t.Log("null, excepted: null")
	lfuCache.Put(10, 13)
	t.Log("null, excepted: null")
	lfuCache.Put(3, 17)
	t.Log("null, excepted: null")
	lfuCache.Put(6, 11)
	t.Log("null, excepted: null")
	lfuCache.Put(10, 5)
	t.Log("null, excepted: null")
	lfuCache.Put(9, 10)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(13), "excepted: -1")
	lfuCache.Put(2, 19)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(2), "excepted: 19")
	t.Log(lfuCache.Get(3), "excepted: 17")
	lfuCache.Put(5, 25)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(8), "excepted: -1")
	lfuCache.Put(9, 22)
	t.Log("null, excepted: null")
	lfuCache.Put(5, 5)
	t.Log("null, excepted: null")
	lfuCache.Put(1, 30)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(11), "excepted: -1")
	lfuCache.Put(9, 12)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(7), "excepted: -1")
	t.Log(lfuCache.Get(5), "excepted: 5")
	t.Log(lfuCache.Get(8), "excepted: -1")
	t.Log(lfuCache.Get(9), "excepted: 12")
	lfuCache.Put(4, 30)
	t.Log("null, excepted: null")
	lfuCache.Put(9, 3)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(9), "excepted: 3")
	t.Log(lfuCache.Get(10), "excepted: 5")
	t.Log(lfuCache.Get(10), "excepted: 5")
	lfuCache.Put(6, 14)
	t.Log("null, excepted: null")
	lfuCache.Put(3, 1)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(3), "excepted: 1")
	lfuCache.Put(10, 11)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(8), "excepted: -1")
	lfuCache.Put(2, 14)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(1), "excepted: 30")
	t.Log(lfuCache.Get(5), "excepted: 5")
	t.Log(lfuCache.Get(4), "excepted: 30")
	lfuCache.Put(11, 4)
	t.Log("null, excepted: null")
	lfuCache.Put(12, 24)
	t.Log("null, excepted: null")
	lfuCache.Put(5, 18)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(13), "excepted: -1")
	lfuCache.Put(7, 23)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(8), "excepted: -1")
	t.Log(lfuCache.Get(12), "excepted: 24")
	lfuCache.Put(3, 27)
	t.Log("null, excepted: null")
	lfuCache.Put(2, 12)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(5), "excepted: 18")
	lfuCache.Put(2, 9)
	t.Log("null, excepted: null")
	lfuCache.Put(13, 4)
	t.Log("null, excepted: null")
	lfuCache.Put(8, 18)
	t.Log("null, excepted: null")
	lfuCache.Put(1, 7)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(6), "excepted: 14")
	lfuCache.Put(9, 29)
	t.Log("null, excepted: null")
	lfuCache.Put(8, 21)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(5), "excepted: 18")
	lfuCache.Put(6, 30)
	t.Log("null, excepted: null")
	lfuCache.Put(1, 12)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(10), "excepted: 11")
	lfuCache.Put(4, 15)
	t.Log("null, excepted: null")
	lfuCache.Put(7, 22)
	t.Log("null, excepted: null")
	lfuCache.Put(11, 26)
	t.Log("null, excepted: null")
	lfuCache.Put(8, 17)
	t.Log("null, excepted: null")
	lfuCache.Put(9, 29)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(5), "excepted: 18")
	lfuCache.Put(3, 4)
	t.Log("null, excepted: null")
	lfuCache.Put(11, 30)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(12), "excepted: -1")
	lfuCache.Put(4, 29)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(3), "excepted: 4")
	t.Log(lfuCache.Get(9), "excepted: 29")
	t.Log(lfuCache.Get(6), "excepted: 30")
	lfuCache.Put(3, 4)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(1), "excepted: 12")
	t.Log(lfuCache.Get(10), "excepted: 11")
	lfuCache.Put(3, 29)
	t.Log("null, excepted: null")
	lfuCache.Put(10, 28)
	t.Log("null, excepted: null")
	lfuCache.Put(1, 20)
	t.Log("null, excepted: null")
	lfuCache.Put(11, 13)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(3), "excepted: 29")
	lfuCache.Put(3, 12)
	t.Log("null, excepted: null")
	lfuCache.Put(3, 8)
	t.Log("null, excepted: null")
	lfuCache.Put(10, 9)
	t.Log("null, excepted: null")
	lfuCache.Put(3, 26)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(8), "excepted: 17")
	t.Log(lfuCache.Get(7), "excepted: -1")
	t.Log(lfuCache.Get(5), "excepted: 18")
	lfuCache.Put(13, 17)
	t.Log("null, excepted: null")
	lfuCache.Put(2, 27)
	t.Log("null, excepted: null")
	lfuCache.Put(11, 15)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(12), "excepted: -1")
	lfuCache.Put(9, 19)
	t.Log("null, excepted: null")
	lfuCache.Put(2, 15)
	t.Log("null, excepted: null")
	lfuCache.Put(3, 16)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(1), "excepted: 20")
	lfuCache.Put(12, 17)
	t.Log("null, excepted: null")
	lfuCache.Put(9, 1)
	t.Log("null, excepted: null")
	lfuCache.Put(6, 19)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(4), "excepted: 29")
	t.Log(lfuCache.Get(5), "excepted: 18")
	t.Log(lfuCache.Get(5), "excepted: 18")
	lfuCache.Put(8, 1)
	t.Log("null, excepted: null")
	lfuCache.Put(11, 7)
	t.Log("null, excepted: null")
	lfuCache.Put(5, 2)
	t.Log("null, excepted: null")
	lfuCache.Put(9, 28)
	t.Log("null, excepted: null")
	t.Log(lfuCache.Get(1), "excepted: 20")
	lfuCache.Put(2, 2)
	t.Log("null, excepted: null")
	lfuCache.Put(7, 4)
	t.Log("null, excepted: null")
	lfuCache.Put(4, 22)
	t.Log("null, excepted: null")
	lfuCache.Put(7, 24)
	t.Log("null, excepted: null")
	lfuCache.Put(9, 26)
	t.Log("null, excepted: null")
	lfuCache.Put(13, 28)
	t.Log("null, excepted: null")
	lfuCache.Put(11, 26)
	t.Log("null, excepted: null")
}

func TestCodeGen(t *testing.T) {
	cmds := []string{"LFUCache", "put", "put", "put", "put", "put", "get", "put", "get", "get", "put", "get", "put", "put", "put", "get", "put", "get", "get", "get", "get", "put", "put", "get", "get", "get", "put", "put", "get", "put", "get", "put", "get", "get", "get", "put", "put", "put", "get", "put", "get", "get", "put", "put", "get", "put", "put", "put", "put", "get", "put", "put", "get", "put", "put", "get", "put", "put", "put", "put", "put", "get", "put", "put", "get", "put", "get", "get", "get", "put", "get", "get", "put", "put", "put", "put", "get", "put", "put", "put", "put", "get", "get", "get", "put", "put", "put", "get", "put", "put", "put", "get", "put", "put", "put", "get", "get", "get", "put", "put", "put", "put", "get", "put", "put", "put", "put", "put", "put", "put"}
	params := []string{"10", "10,13", "3,17", "6,11", "10,5", "9,10", "13", "2,19", "2", "3", "5,25", "8", "9,22", "5,5", "1,30", "11", "9,12", "7", "5", "8", "9", "4,30", "9,3", "9", "10", "10", "6,14", "3,1", "3", "10,11", "8", "2,14", "1", "5", "4", "11,4", "12,24", "5,18", "13", "7,23", "8", "12", "3,27", "2,12", "5", "2,9", "13,4", "8,18", "1,7", "6", "9,29", "8,21", "5", "6,30", "1,12", "10", "4,15", "7,22", "11,26", "8,17", "9,29", "5", "3,4", "11,30", "12", "4,29", "3", "9", "6", "3,4", "1", "10", "3,29", "10,28", "1,20", "11,13", "3", "3,12", "3,8", "10,9", "3,26", "8", "7", "5", "13,17", "2,27", "11,15", "12", "9,19", "2,15", "3,16", "1", "12,17", "9,1", "6,19", "4", "5", "5", "8,1", "11,7", "5,2", "9,28", "1", "2,2", "7,4", "4,22", "7,24", "9,26", "13,28", "11,26"}
	excepted := []string{"null", "null", "null", "null", "null", "null", "-1", "null", "19", "17", "null", "-1", "null", "null", "null", "-1", "null", "-1", "5", "-1", "12", "null", "null", "3", "5", "5", "null", "null", "1", "null", "-1", "null", "30", "5", "30", "null", "null", "null", "-1", "null", "-1", "24", "null", "null", "18", "null", "null", "null", "null", "14", "null", "null", "18", "null", "null", "11", "null", "null", "null", "null", "null", "18", "null", "null", "-1", "null", "4", "29", "30", "null", "12", "11", "null", "null", "null", "null", "29", "null", "null", "null", "null", "17", "-1", "18", "null", "null", "null", "-1", "null", "null", "null", "20", "null", "null", "null", "29", "18", "18", "null", "null", "null", "null", "20", "null", "null", "null", "null", "null", "null", "null"}
	for idx, cmd := range cmds {
		switch cmd {
		case "LFUCache":
			fmt.Printf("lfuCache := Constructor(%s)\n", params[idx])
			fmt.Printf("t.Log(\"null, excepted: %s\")\n", excepted[idx])
		case "put":
			fmt.Printf("lfuCache.Put(%s)\n", params[idx])
			fmt.Printf("t.Log(\"null, excepted: %s\")\n", excepted[idx])
		case "get":
			fmt.Printf("t.Log(lfuCache.Get(%s), \"excepted: %s\")\n", params[idx], excepted[idx])
		}
	}
}
